CACHES:
    default:
        BACKEND: redis_cache.RedisCache
        LOCATION: redis://redis:6379
        OPTIONS:
            DB: 1
            PARSER_CLASS: redis.connection.HiredisParser

DATABASES:
    default:
        ENGINE: django.db.backends.postgresql_psycopg2
        HOST: postgres
        PORT: 5432

CELERY_BROKER_URL: redis://redis:6379/0
CELERY_BEAT_SCHEDULE:
    cache-crls:
        task: django_ca.tasks.cache_crls
        schedule: 86100
    generate-ocsp-keys:
        # schedule is three days minus five minutes, since keys expire after
        # three days by default.
        task: django_ca.tasks.generate_ocsp_keys
        schedule: 258900
