# Configuration for django-ca. You can add/update settings here and then
# restart your containers.

# Secret key used for session handling etc, must be a long, random string.
# Generate with:
#
#   {{ RANDOM_COMMAND }}
#
SECRET_KEY: "{{ SECRET_KEY }}"

# Where to find your database
DATABASES:
    default:
        ENGINE: django.db.backends.postgresql
        HOST: "{{ POSTGRES_HOST }}"
        PORT: 5432
        PASSWORD: "{{ POSTGRES_PASSWORD }}"

# Shared, persistent cache
CACHES:
    default:
        BACKEND: django.core.cache.backends.redis.RedisCache
        LOCATION: redis://{{ REDIS_HOST }}:6379
        OPTIONS:
            db: "1"

# django-ca will use Celery as an asynchronous task worker
CELERY_BROKER_URL: redis://{{ REDIS_HOST }}:6379/0

# Default hostname to use when generating CRLs and OCSP responses
CA_DEFAULT_HOSTNAME: "{{ CA_DEFAULT_HOSTNAME }}"
